var searchData=
[
  ['raman_20board_0',['Raman Board',['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2RoveComm_2README.html#autotoc_md70',1,'']]],
  ['random_1',['random',['../BS__thread__pool__test_8cpp.html#a3df8292797bff15c9c5b8db3e1ddd2b6',1,'BS_thread_pool_test.cpp']]],
  ['random_5fpair_2',['random_pair',['../BS__thread__pool__test_8cpp.html#a249b6807c999d082bc60c88faa19d350',1,'BS_thread_pool_test.cpp']]],
  ['readme_3',['readme',['../md_Source_2ThirdParty_2RoveComm__CPP_2tools_2valgrind_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2tools_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2tests_2Unit_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2tests_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2tests_2Integration_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2src_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2ASCII_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html',1,'README'],['../md_Source_2ThirdParty_2RoveComm__CPP_2docs_2README.html',1,'README']]],
  ['ready_4',['ready',['../classBS_1_1signaller.html#ac61ee6474c6f49ca28aad6772aa4a04e',1,'BS::signaller']]],
  ['ready_5fcount_5',['ready_count',['../classBS_1_1multi__future.html#a0d35113924256a7449a02faf27e3de5f',1,'BS::multi_future']]],
  ['receiving_20a_20future_6',['receiving a future',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md115',1,'Submitting tasks with arguments and receiving a future'],['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md114',1,'Submitting tasks with no arguments and receiving a future']]],
  ['reference_7',['reference',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md150',1,'Complete library reference'],['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md136',1,'Passing task arguments by constant reference']]],
  ['report_8',['report',['../CONTRIBUTING.html#autotoc_md3',1,'Before Submitting a Bug Report'],['../CONTRIBUTING.html#autotoc_md4',1,'How Do I Submit a Good Bug Report?']]],
  ['reporting_20bugs_9',['Reporting Bugs',['../CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['repository_10',['Starring the repository',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md163',1,'']]],
  ['request_20policy_11',['Issue and pull request policy',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md161',1,'']]],
  ['requests_12',['Pull Requests',['../CONTRIBUTING.html#autotoc_md9',1,'']]],
  ['reset_13',['reset',['../classBS_1_1thread__pool.html#a45ebb337e3b7e4671352e4f3c67f7311',1,'BS::thread_pool::reset(const concurrency_t num_threads, const std::function&lt; void()&gt; &amp;init_task)'],['../classBS_1_1thread__pool.html#a8b4172f1d76163c55e5d43e5835b23ef',1,'BS::thread_pool::reset()'],['../classBS_1_1thread__pool.html#a266a535346ea77b26da30a05a0f95a38',1,'BS::thread_pool::reset(const concurrency_t num_threads)'],['../classBS_1_1thread__pool.html#a52bdb7f9cb1520779c1a71f8c3123d34',1,'BS::thread_pool::reset(const std::function&lt; void()&gt; &amp;init_task)']]],
  ['resetting_20the_20number_20of_20threads_20in_20the_20pool_14',['Getting and resetting the number of threads in the pool',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md111',1,'']]],
  ['return_20values_15',['Loops with return values',['../md_Source_2ThirdParty_2RoveComm__CPP_2external_2threadpool_2README.html#autotoc_md123',1,'']]],
  ['rovecomm_20base_16',['RoveComm Base',['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2RoveComm_2README.html',1,'']]],
  ['rovecomm_20c_17',['rovecomm c',['../CONTRIBUTING.html#autotoc_md0',1,'Contributing to RoveComm C++'],['../index.html#autotoc_md166',1,'RoveComm C++']]],
  ['rovecomm_20c_20api_20docs_20here_20a_18',['&lt;a href=&quot;https://missourimrdt.github.io/RoveComm_CPP/&quot; &gt;RoveComm C++ API Docs HERE&lt;/a&gt;',['../index.html#autotoc_md168',1,'']]],
  ['rovecomm_20manifest_19',['RoveComm Manifest',['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2RoveComm_2README.html#autotoc_md28',1,'']]],
  ['rovecomm_5fcpp_20rovecomm_20c_20api_20docs_20here_20a_20',['&lt;a href=&quot;https://missourimrdt.github.io/RoveComm_CPP/&quot; &gt;RoveComm C++ API Docs HERE&lt;/a&gt;',['../index.html#autotoc_md168',1,'']]],
  ['rovecommdata_21',['RoveCommData',['../structrovecomm_1_1RoveCommData.html',1,'rovecomm']]],
  ['rovecommpacket_22',['RoveCommPacket',['../structrovecomm_1_1RoveCommPacket.html',1,'rovecomm']]],
  ['rovecommtcp_23',['RoveCommTCP',['../classrovecomm_1_1RoveCommTCP.html',1,'rovecomm']]],
  ['rovecommudp_24',['RoveCommUDP',['../classrovecomm_1_1RoveCommUDP.html',1,'rovecomm']]],
  ['rovesosimulator_25',['RoveSoSimulator',['../index.html',1,'']]],
  ['rovesosimulator_20board_26',['RoveSoSimulator Board',['../md_Source_2ThirdParty_2RoveComm__CPP_2data_2RoveComm_2README.html#autotoc_md74',1,'']]]
];
